config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount SwaggerUI, at: 'docs/api'
  mount API => 'api'

  namespace :admin do
    resources :stations
    resources :users
  end

  resources :drivers do
    member do
       put 'reset_tag_assignment'
    end
  end
  resources :races do
    resources :teams do
      collection do
        post 'handle_team_login'
        post 'import'
      end

      member do
        post 'move_up'
        post 'move_down'
        post 'set_registrating'
      end
    end
    resources :events, only: [:index, :create, :destroy] do
      member do
        get 'details'
        post 'adjust'
      end
    end
    resources :penalties, only: [:index]

    member do
      get 'public_overview'
      get 'overview'
      get 'settings'

      # AASM events
      post 'start'
      post 'finish'
      post 'stop_registrating'
    end
  end

  root to: 'races#current'
end

app/models/race.rb
# == Schema Information
#
# Table name: races
#
#  id                   :integer          not null, primary key
#  name                 :string(255)
#  duration             :integer
#  max_drive            :integer
#  max_turn             :integer
#  break_time           :integer
#  waiting_period       :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  slug                 :string(255)
#  state                :integer          default(0)
#  mode                 :integer          default(0)
#  scheduled            :date
#  started_at           :datetime
#  finished_at          :datetime
#  min_turn             :integer
#  prebooking_open      :boolean          default(FALSE)
#  registrating_team_id :integer
#
# Indexes
#
#  index_races_on_mode  (mode)
#  index_races_on_slug  (slug)
#



class Race < ActiveRecord::Base
  extend FriendlyId
  include AASM

  enum state: {
    planned: 0,
    active: 5,
    finished: 10
  }

  enum mode: {
    both: 0,
    leaving: 5
  }

  aasm column: :state do
    state :planned, initial: true
    state :active
    state :finished

    event :start do
      after do
        self.started_at = Time.zone.now
      end
      transitions from: :planned, to: :active
    end

    event :finish do
      after do
        create_events_on_finish
        self.finished_at = Time.zone.now
      end
      transitions from: :active, to: :finished
    end
  end

  has_many :teams, dependent: :destroy

  validates :name, :scheduled, presence: true
  friendly_id :name, use: :slugged

  def attendances
    Attendance.where(team_id: teams.select(:id))
  end

  def drivers
    Driver.where(id: Attendance.where(team_id: teams.select(:id)).select(:driver_id))
  end

  def events
    Event.where(team_id: teams.select(:id))
  end

  def create_events_on_finish
    active_drivers = to_stats
      .group_by_team
      .reject{|team_id, stats| stats.current_driver_id.nil? }
      .map{|team_id, stats| [team_id, stats.current_driver_id] }

    active_drivers.each do |team_id, driver_id|
      Event.create team_id:team_id, driver_id:driver_id
    end
  end

  def penalties
    Penalty.where(team_id: teams.select(:id))
  end

  def race_duration
    return 0 unless active?
    return finished_at.to_time - started_at.to_time if finished?

    Time.zone.now - started_at.to_time
  end

  def race_time
    return unless active?
    return finished_at.to_time if finished?

    Time.at(race_duration)
  end

  def to_stats
    events = Event.where(team_id: teams.select(:id)).map do |e|
      ts = if self.started_at.present?
        e.created_at < self.started_at ? self.started_at : e.created_at
      else
        e.created_at
      end
      [e.team_id, e.driver_id, ts.to_time.utc.to_i, e.mode]
    end
    turns  = Turn.where(team_id: teams.select(:id)).map { |t| [t.team_id, t.driver_id, t.duration] }
    penalties = Penalty.where(team_id: teams.select(:id)).map { |pe| [pe.team_id, pe.driver_id, pe.created_at.to_time.utc.to_i, pe.reason] }
    Stats.new events, turns, penalties, mode
  end

  def self.current_race?
    current_race.present?
  end

  def self.current_race
    Race.active.first || Race.planned.where('scheduled>=?', Date.current).order(scheduled: :asc).first
  end
end

app/controllers/races_controller.rb
# == Schema Information
#
# Table name: races
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  duration       :integer
#  max_drive      :integer
#  max_turn       :integer
#  break_time     :integer
#  waiting_period :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  slug           :string(255)
#  state          :integer
#  mode           :integer
#  scheduled      :date
#  started_at     :datetime
#  finished_at    :datetime
#
# Indexes
#
#  index_races_on_mode  (mode)
#  index_races_on_slug  (slug)
#

class RacesController < ApplicationController
  include RacesHelper
  before_action :set_race, except: [:index, :current, :new, :create]
  skip_before_filter :authenticate_user!, only:[:current, :public_overview]

  # GET /races
  # GET /races.json
  def index
    @q = Race.ransack(params[:q])
    @q.sorts = 'state asc' if @q.sorts.empty?
    page = (params[:page] || '1').to_i
    @races = @q.result.page(page)
  end

  def stop_registrating
    @race.update(registrating_team_id: nil)
    flash[:notice] = 'Registrierung wurde gestoppt'
    redirect_to race_teams_url(@race)
  end


  def current
    if c = current_race
      redirect_to c
      return
    end
    redirect_to races_path
  end

  # POST /races/1/start
  def start
    flash[:notice] = 'Das Rennen wurde gestartet' if @race.start && @race.save
    redirect_to settings_race_path(@race)
  end

  # POST /races/1/finish
  def finish
    flash[:notice] = 'Das Rennen wurde beendet' if @race.finish && @race.save
    redirect_to settings_race_path(@race)
  end

  # GET /races/1
  # GET /races/1.json
  def show
    session[:current_race] = @race.id
    redirect_to settings_race_path(@race)
  end

  # GET /races/1/overview
  def overview
  end

  # GET /races/1/public_overview
  def public_overview
    render layout:'public'
  end

  # GET /races/1/settings
  def settings
  end

  # GET /races/new
  def new
    @race = Race.new mode: :both, duration: 540, max_drive: 170, min_turn: 20, max_turn: 40, break_time: 45, waiting_period: 3
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: I18n.t(:create, scope: 'messages.crud', model: Race.model_name.human) }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: I18n.t(:update, scope: 'messages.crud', model: Race.model_name.human) }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: I18n.t(:destroy, scope: 'messages.crud', model: Race.model_name.human) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_race
    @race = Race.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def race_params
    params.require(:race).permit :name, :duration, :mode, :max_drive, :max_turn, :min_turn, :break_time, :waiting_period, :scheduled, :prebooking_open
  end
end

app/helpers/races_helper.rb
# == Schema Information
#
# Table name: races
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  duration       :integer
#  max_drive      :integer
#  max_turn       :integer
#  break_time     :integer
#  waiting_period :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  slug           :string(255)
#  state          :integer
#  mode           :integer
#  scheduled      :date
#  started_at     :datetime
#  finished_at    :datetime
#
# Indexes
#
#  index_races_on_mode  (mode)
#  index_races_on_slug  (slug)
#

module RacesHelper
  def current_race?
    current_race.present?
  end

  def current_race
    current_race = begin
      Race.find(session[:current_race]) if session.key?(:current_race)
    rescue ActiveRecord::RecordNotFound
      Rails.logger.error "Invalid race ID in session: #{session[:current_race]}"
      session.delete :current_race
      nil
    end
    current_race ||= Race.current_race

    current_race
  end

  def minutes_to_time(total_minutes)
    minutes = total_minutes % 60
    hours = total_minutes / 60

    return format('%02d Stunden %02d Minuten', hours, minutes) if hours > 0
    format('%02d Minuten', minutes)
  end
end

app/views/races/_form.html.haml
= simple_form_for @race do |f|
  = f.error_notification

  .row
    = f.input :name, wrapper_html:{ class:'col-sm-9' }
    = f.input :mode, as: :radio_buttons, collection:Race.modes.map{|k, _v| [I18n.t(k, scope:'race.modes'), k]}, wrapper_html:{ class:'col-sm-3' }

  .row
    = f.input :prebooking_open, inline_label: true, wrapper_html:{ class:'col-sm-3 col-sm-push-9' }
    = f.input :scheduled, wrapper_html:{ class:'col-sm-9 col-sm-pull-3' }

  .row
    = f.input :duration, hint:'In Minuten', wrapper_html:{ class:'col-sm-3' }
    = f.input :min_turn, hint:'In Minuten', wrapper_html:{ class:'col-sm-3' }
    = f.input :max_turn, hint:'In Minuten', wrapper_html:{ class:'col-sm-3' }

  .row
    = f.input :max_drive, hint:'In Minuten', wrapper_html:{ class:'col-sm-3' }
    = f.input :break_time, hint:'In Minuten', wrapper_html:{ class:'col-sm-3' }
    = f.input :waiting_period, hint:'In Minuten', wrapper_html:{ class:'col-sm-3' }

  = f.button :submit, class:'btn-primary'
  = link_to t('cancel'), @race, class:'btn btn-link'

app/views/races/_header.html.haml
- if @race.active?
  .row
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'clock-o', class:'text-muted'
            %span.timer{ data:{ mode:'timer', start:current_race.started_at.to_time.to_i*1000 } }= time_format current_race.race_time.utc
        .panel-footer
          %h4.panel-title.text-center Rennzeit
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'arrow-circle-o-right', class:'text-muted'
            %span.timer{ data:{ mode:'countdown', duration:current_race.duration*60, start:current_race.started_at.to_time.to_i*1000 } }
        .panel-footer
          %h4.panel-title.text-center Rest
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'users', class:'text-muted'
            = @race.teams.count
        .panel-footer
          %h4.panel-title.text-center Anzahl Teams
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'user', class:'text-muted'
            = @race.to_stats.active_driver_count
        .panel-footer
          %h4.panel-title.text-center Anzahl aktive Fahrer

%ul.nav.nav-tabs
  = nav_link_to overview_race_path(@race) do
    = fa_icon 'tachometer'
    Aktueller Stand
  = nav_link_to race_teams_path(@race) do
    = fa_icon 'users'
    Teams
  = nav_link_to race_events_path(@race) do
    = fa_icon 'info-circle'
    Events
  = nav_link_to settings_race_path(@race) do
    = fa_icon 'wrench'
    Einstellungen
  = yield :subnav

app/views/races/edit.html.haml
%h1 Rennen bearbeiten

.row
  .col-md-8
    = render 'form'

app/views/races/index.html.haml
%h1 Alle Rennen

%table.table.table-striped
  %colgroup
    %col{ width:120 }
    %col
    %col{ width:180 }
    %col{ width:110 }
    %col{ width:110 }
  %thead
    %tr
      %th= sort_link @q, :state
      %th= sort_link @q, :name
      %th.text-center= sort_link @q, :scheduled
      %th
      %th

  - if @races.any?
    %tbody
      - @races.each do |race|
        %tr
          %td
            %span.label.label-default= t race.state, scope:'race.states'
          %td= link_to race.name, race
          %td.text-center= l race.scheduled
          %td.text-right
            = link_to edit_race_path(race) do
              = fa_icon 'edit fw'
              = t(:edit)
          %td.text-right
            = destroy_link_to race
  - else
    %tbody
      %tr.info
        %td{ colspan:5 }
          %p.text-center Keine Rennen angelegt.

= paginate @races

%p
  = link_to 'Neues Rennen', new_race_path, class:'btn btn-primary'

app/views/races/new.html.haml
%h1 Neues Rennen anlegen

.row
  .col-md-8
    = render 'form'

app/views/races/overview.html.haml
- content_for :subnav do
  %li.pull-right.hidden-xs.hidden-sm
    %form.form-inline{ style:'margin-top: 6px'}
      .form-group
        %label.control-label{ for:'search' } Filter
        %input.form-control.input-sm#search{ type:'search', placeholder:'Teamname', autocomplete:'off' }
  %li.pull-right
    = link_to public_overview_race_path(@race), target:'_blank' do
      = fa_icon 'television'
      Externe Ansicht

= render partial:'header'

.content
  %ul.block-grid-xs-2.block-grid-sm-4.block-grid-md-6.block-grid-lg-8
    - stats = @race.to_stats.group_by_team
    - @race.teams.includes(:attendances).each do |team|
      %li.team{ data:{ name:team.name.downcase } }
        = render partial:'teams/team', locals:{ race:@race, team:team, stats:stats[team.id] }

- content_for :head do
  %meta{ 'http-equiv' => 'refresh', content:30 }

- content_for :bottom do
  :coffee
    $ ->
      $(document).on 'timer:error', (evt, diff) ->
        $(evt.target).toggleClass 'error', true
        $(evt.target).closest('.panel').removeClass('panel-secondary panel-info').addClass('panel-danger')
      $(document).on 'timer:warning', (evt, diff) ->
        $(evt.target).toggleClass 'warning', true
      $('#search').keyup ->
        $('.team').show()
        if $(this).val() != ''
          $('.team').not('[data-name*="' + $(this).val() + '"]').hide()

app/views/races/public_overview.html.haml
- if @race.active?
  .row
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'clock-o', class:'text-muted'
            %span.timer{ data:{ mode:'timer', start:current_race.started_at.to_time.to_i*1000 } }= time_format current_race.race_time.utc
        .panel-footer
          %h4.panel-title.text-center Rennzeit
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'arrow-circle-o-right', class:'text-muted'
            %span.timer{ data:{ mode:'countdown', duration:current_race.duration*60, start:current_race.started_at.to_time.to_i*1000 } }
        .panel-footer
          %h4.panel-title.text-center Rest
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'users', class:'text-muted'
            = @race.teams.count
        .panel-footer
          %h4.panel-title.text-center Anzahl Teams
    .col-xs-6.col-md-3
      .panel.panel-info.card
        .panel-body
          .text-center.text-large
            = fa_icon 'user', class:'text-muted'
            = @race.to_stats.active_driver_count
        .panel-footer
          %h4.panel-title.text-center Anzahl aktive Fahrer

.content
  %ul.block-grid-xs-2.block-grid-sm-4.block-grid-md-6.block-grid-lg-8
    - stats = @race.to_stats.group_by_team
    - @race.teams.includes(:events, :drivers).each do |team|
      %li.team{ data:{ name:team.name.downcase } }
        = render partial:'teams/team', locals:{ race:@race, team:team, stats:stats[team.id] }

- content_for :bottom do
  :coffee
    $ ->
      $(document).on 'timer:error', (evt, diff) ->
        $(evt.target).toggleClass 'error', true
        $(evt.target).closest('.panel').removeClass('panel-secondary panel-info').addClass('panel-danger')
      $(document).on 'timer:warning', (evt, diff) ->
        $(evt.target).toggleClass 'warning', true
      $('#search').keyup ->
        $('.team').show()
        if $(this).val() != ''
          $('.team').not('[data-name*="' + $(this).val() + '"]').hide()

app/views/races/settings.html.haml
= render partial:'header'

.content
  .row
    .col-sm-6
      .content
        .panel.panel-default.panel-info.panel-compact
          .panel-heading
            %h3.panel-title Stammdaten
          %table.table
            %colgroup
              %col{ width:'40%' }
              %col
            %tbody
              %tr
                %th= Race.human_attribute_name :name
                %td= @race.name
              %tr
                %th= Race.human_attribute_name :teams
                %td
                  = link_to race_teams_path(@race) do
                    = @race.teams.count
                    = Team.model_name.human(count:@race.teams.count)
              %tr
                %th= Race.human_attribute_name :state
                %td= t @race.state, scope:'race.states'
              %tr
                %th= Race.human_attribute_name :scheduled
                %td= l @race.scheduled
              %tr
                %th= Race.human_attribute_name :started_at
                %td= l @race.started_at if @race.started_at
              %tr
                %th= Race.human_attribute_name :finished_at
                %td= l @race.finished_at if @race.finished_at
              %tr
                %th= Race.human_attribute_name :created_at
                %td= l @race.created_at
              %tr
                %th= Race.human_attribute_name :updated_at
                %td= l @race.updated_at

    .col-sm-6
      .content
        .panel.panel-default.panel-info.panel-compact
          .panel-heading
            %h3.panel-title Einstellungen
          %table.table
            %colgroup
              %col{ width:'40%' }
              %col
            %tbody
              %tr
                %th= Race.human_attribute_name :mode
                %td= t @race.mode, scope:'race.modes'
              %tr
                %th= Race.human_attribute_name :prebooking_open
                %td
                  - if @race.prebooking_open
                    %span.label.label-success{ title:'Vorabbuchungen möglich', data:{toggle:'tooltip', placement:'bottom'} } Ja
                  -else
                    %span.label.label-danger{ title:'Vorabbuchungen noch nicht möglich', data:{toggle:'tooltip', placement:'bottom'} } Nein
              %tr
                %th= Race.human_attribute_name :duration
                %td= minutes_to_time @race.duration
              %tr
                %th= Race.human_attribute_name :max_drive
                %td= minutes_to_time @race.max_drive
              %tr
                %th= Race.human_attribute_name :min_turn
                %td= minutes_to_time @race.min_turn
              %tr
                %th= Race.human_attribute_name :max_turn
                %td
                  = minutes_to_time @race.max_turn
                  + #{minutes_to_time @race.waiting_period} Karenz
              %tr
                %th= Race.human_attribute_name :break_time
                %td= minutes_to_time @race.break_time

  %p
    .pull-right
      - @race.aasm.events.each do |evt|
        = link_to t(evt.name, scope:'race.events'), {action:evt.name}, method: :post, class:'btn btn-secondary', data:{ confirm:'Wollen Sie den Rennstatus jetzt verändern?', ok:t('buttons.ok'), cancel:t('buttons.cancel') }
    = link_to t('edit'), edit_race_path(@race), class:'btn btn-primary'
    = link_to t('back'), races_path, class:'btn btn-text'