config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount SwaggerUI, at: 'docs/api'
  mount API => 'api'

  namespace :admin do
    resources :stations
    resources :users
  end

  resources :drivers do
    member do
       put 'reset_tag_assignment'
    end
  end
  resources :races do
    resources :teams do
      collection do
        post 'handle_team_login'
        post 'import'
      end

      member do
        post 'move_up'
        post 'move_down'
        post 'set_registrating'
      end
    end
    resources :events, only: [:index, :create, :destroy] do
      member do
        get 'details'
        post 'adjust'
      end
    end
    resources :penalties, only: [:index]

    member do
      get 'public_overview'
      get 'overview'
      get 'settings'

      # AASM events
      post 'start'
      post 'finish'
      post 'stop_registrating'
    end
  end

  root to: 'races#current'
end

app/models/station.rb
# == Schema Information
#
# Table name: stations
#
#  id         :integer          not null, primary key
#  token      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_stations_on_token  (token)
#


class Station < ActiveRecord::Base
  validates :token, presence: true, format: { with: /\A\h+\z/, message: :hex_only }, length: { is: 12 }, uniqueness: true
  before_validation :convert_token

  private

  def convert_token
    return if token.blank?
    token.gsub!(/\s+/, '')
    token.upcase!
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    page = (params[:page] || '1').to_i
    @stations = Station.page(page)
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to admin_stations_url, notice: I18n.t(:create, scope: 'messages.crud', model: Station.model_name.human) }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to [:admin, @station], notice: I18n.t(:update, scope: 'messages.crud', model: Station.model_name.human) }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to admin_stations_url, notice: I18n.t(:destroy, scope: 'messages.crud', model: Station.model_name.human) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_station
    @station = Station.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def station_params
    params.require(:station).permit(:token)
  end
end

app/helpers/admin/stations_helper.rb
module Admin::StationsHelper
end

app/views/admin/stations/_form.html.haml
= simple_form_for [:admin, @station] do |f|
  = f.error_notification
  = f.input :token, placeholder:'12-stelliger Hex Code', input_html:{ class:'monospace' }

  = f.button :submit, class:'btn-primary'
  = link_to t('cancel'), admin_stations_path, class:'btn btn-link'

app/views/admin/stations/edit.html.haml
.panel.panel-default
  .panel-heading Station bearbeiten
  .panel-body
    = render 'form'

app/views/admin/stations/index.html.haml
%h1 Registrierte Lesestationen

%table.table.table-striped
  %colgroup
    %col
    %col{ width:80 }
    %col{ width:110 }
  %thead
    %tr
      %th Token
      %th
      %th

  - if @stations.any?
    %tbody
      - @stations.each do |station|
        %tr
          %td.monospace= link_to station.token, [:admin, station]
          %td= link_to 'Bearbeiten', edit_admin_station_path(station)
          %td= destroy_link_to [:admin, station]
  - else
    %tbody
      %tr.info
        %td{ colspan:3 }
          %p.text-center Keine Stationen angelegt.

= paginate @stations

= link_to 'Neue Lesestation', new_admin_station_path, class:'btn btn-primary'

app/views/admin/stations/new.html.haml
.panel.panel-default
  .panel-heading Neue Station anlegen
  .panel-body
    = render 'form'

app/views/admin/stations/show.html.haml
%h1= @station.token

%p
  = link_to t('edit'), edit_admin_station_path(@station), class:'btn btn-primary'
  = link_to t('back'), admin_stations_path, class:'btn btn-link'