config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount SwaggerUI, at: 'docs/api'
  mount API => 'api'

  namespace :admin do
    resources :stations
    resources :users
  end

  resources :drivers do
    member do
       put 'reset_tag_assignment'
    end
  end
  resources :races do
    resources :teams do
      collection do
        post 'handle_team_login'
        post 'import'
      end

      member do
        post 'move_up'
        post 'move_down'
        post 'set_registrating'
      end
    end
    resources :events, only: [:index, :create, :destroy] do
      member do
        get 'details'
        post 'adjust'
      end
    end
    resources :penalties, only: [:index]

    member do
      get 'public_overview'
      get 'overview'
      get 'settings'

      # AASM events
      post 'start'
      post 'finish'
      post 'stop_registrating'
    end
  end

  root to: 'races#current'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#


class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    page = (params[:page] || '1').to_i
    @users = User.page(page)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: I18n.t(:create, scope: 'messages.crud', model: User.model_name.human) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: I18n.t(:update, scope: 'messages.crud', model: User.model_name.human) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: I18n.t(:destroy, scope: 'messages.crud', model: User.model_name.human) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.haml
= simple_form_for([:admin, @user]) do |f|
  = f.error_notification
  = f.input :email
  = f.input :password
  = f.input :password_confirmation

  = f.button :submit, class:'btn-primary'
  = link_to t('cancel'), admin_users_path, class:'btn btn-link'
  

app/views/admin/users/edit.html.haml
.panel.panel-default
  .panel-heading Benutzer bearbeiten
  .panel-body
    = render 'form'

app/views/admin/users/index.html.haml
%h1 Bekannte Anwender

%table.table.table-striped
  %colgroup
    %col
    %col{ width:80 }
    %col{ width:110 }
  %thead
    %tr
      %th Email
      %th
      %th

  - if @users.any?
    %tbody
      - @users.each do |user|
        %tr
          %td.monospace= link_to user.email, [:admin, user]
          %td= link_to 'Bearbeiten', edit_admin_user_path(user)
          %td= destroy_link_to [:admin, user]
  - else
    %tbody
      %tr.info
        %td{ colspan:3 }
          %p.text-center Keine Anwender angelegt.

= paginate @users

= link_to 'Neuer Anwender', new_admin_user_path, class:'btn btn-primary'

app/views/admin/users/new.html.haml
.panel.panel-default
  .panel-heading Neuen Anwender anlegen
  .panel-body
    = render 'form'

app/views/admin/users/show.html.haml
%h1= @user.email

%p
  = link_to t('edit'), edit_admin_user_path(@user), class:'btn btn-primary'
  = link_to t('back'), admin_users_path, class:'btn btn-link'