config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount SwaggerUI, at: 'docs/api'
  mount API => 'api'

  namespace :admin do
    resources :stations
    resources :users
  end

  resources :drivers do
    member do
       put 'reset_tag_assignment'
    end
  end
  resources :races do
    resources :teams do
      collection do
        post 'handle_team_login'
        post 'import'
      end

      member do
        post 'move_up'
        post 'move_down'
        post 'set_registrating'
      end
    end
    resources :events, only: [:index, :create, :destroy] do
      member do
        get 'details'
        post 'adjust'
      end
    end
    resources :penalties, only: [:index]

    member do
      get 'public_overview'
      get 'overview'
      get 'settings'

      # AASM events
      post 'start'
      post 'finish'
      post 'stop_registrating'
    end
  end

  root to: 'races#current'
end

app/views/layouts/_footer.html.haml
.container-fluid
  %ul.footer-links.pull-right
    %li= link_to 'API', '/docs/api/' if user_signed_in?
    %li
  %ul.footer-links
    %li
      %strong TeamControl
      &copy; #{Time.now.year}
      %span.text-muted= Teamcontrol::Application.version

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - s = { notice:'success', warning:'warning', error:'danger', alert:'danger' }[name.to_s.to_sym]
    %div{:class => "alert alert-#{s}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    - if user_signed_in?
      .navbar-header
        %button.navbar-toggle{ type:'button', data:{ target:'.navbar-collapse', toggle:'collapse'} }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        - if current_race?
          = link_to root_path, class: 'navbar-brand' do
            = fa_icon 'flag-checkered'
            = current_race.name
      .collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li= link_to 'Fahrer', drivers_path
          %li= link_to 'Rennen', races_path
          %li.dropdown
            %a.dropdown-toggle{ href:'#', role:'button', data:{toggle:'dropdown'} }
              Verwaltung
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'Stationen', admin_stations_path
              %li= link_to 'Anwender', admin_users_path
          %li= link_to 'Abmelden', destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Teamcontrol'
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-128x128.png', rel: 'apple-touch-icon', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    = yield :head
  %body
    %header
      = render 'layouts/navigation'
    .main{ role:'main' }
      .container-fluid
        = render 'layouts/messages'
        = yield
    %footer
      = render 'layouts/footer'
    = javascript_include_tag 'application'
    = yield :bottom

app/views/layouts/public.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ 'http-equiv' => 'refresh', content:30 }
    %title= content_for?(:title) ? yield(:title) : 'Teamcontrol'
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = favicon_link_tag 'apple-touch-icon-128x128.png', rel: 'apple-touch-icon', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body.public
    .main{ role:'main' }
      .container-fluid
        = yield
    %footer
      = render 'layouts/footer'
    = javascript_include_tag 'application'
    = yield :bottom